source 'https://rubygems.org'

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
  end

gem 'jekyll'
gem "github-pages", "~> 3.8.5", group: :jekyll_plugins